#-*-Makefile-*-
# /***************************************************************************
# *                                                                          *
# * INSERT COPYRIGHT HERE!                                                   *
# *                                                                          *
# ****************************************************************************
# */
bldall clean depend :
	cd scanning_03     && $(MAKE) $@
	cd scanning_04     && $(MAKE) $@
	cd scanning_05     && $(MAKE) $@
	cd scanning_06     && $(MAKE) $@

test :
	cd scanning_03     && $(MAKE) $@
	cd scanning_04     && $(MAKE) $@
	cd scanning_05     && $(MAKE) $@
	cd scanning_06     && $(MAKE) $@