# PURPOSE: nwkAddrMap routines test makefile
# */

BUILD_HOME=../..
include $(BUILD_HOME)/Options

SRCS=nwk_addr_test.c

$(BIN)nwk_addr_test$(EXE) : $(OBJS) $(LIBS)
	$(LINK_BINARY)

BINS = $(BIN)nwk_addr_test$(EXE)

BINS_TEST=$(BINS)

all: $(BINS)
